/* MTI_DPI */

/*
 * Copyright 2002-2011 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPI_MI32_WRAPPER_PKG
#define INCLUDED_DPI_MI32_WRAPPER_PKG

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
void
c_readFromRegister(
    const svBitVecVal* hw_addr,
    svBitVecVal* hw_data);

DPI_LINK_DECL DPI_DLLESPEC
void
c_writeToRegister(
    const svBitVecVal* hw_addr,
    const svBitVecVal* hw_data);

#endif 
