/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Thu Jan 17 15:32:01 2013, generated by Codasip HW generator v1.6.0.
 *  \brief  Definition of the OVM test class.
 */

// This class is OVM test for codix_ca
class codix_ca_test extends ovm_test;

	// reference to all interfaces
	local DutIfWrapper if_wrapper;
	// member attribute with the verification environment
	local codix_ca_env m_codix_ca_env;

	// registration of component tools
	`ovm_component_utils_begin( codix_ca_test )
		`ovm_field_object( if_wrapper, OVM_DEFAULT | OVM_NOCOMPARE | OVM_NOPRINT | OVM_NORECORD | OVM_NOPACK )
	`ovm_component_utils_end

	// Constructor - creates new instance of this class
	function new( string name, ovm_component parent );
		super.new( name, parent );
	endfunction: new

	// build - instantiates child components
	function void build();
		super.build();
		m_codix_ca_env = new( "m_codix_ca_env", this );
	endfunction: build

	// run - runs the simulation
	task run();
		// wait for the halt instruction
		while ( !if_wrapper.ihalt_if.is_active() )
			@(if_wrapper.ihalt_if.cb);
		#(CLK_PERIOD);
		global_stop_request();
	endtask: run

endclass: codix_ca_test
