/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Mon Mar  4 13:49:04 2013, generated by Codasip HW generator v2.0.0.
 *  \brief  Contains SystemVerilog environment constants.
 */

package sv_codix_ca_param_pkg;


    /*
     * Enumeration type for Framework type
     * SW = software
     * HW = hardware
     */ 
     typedef enum {SW_FULL,           
                   SW_HW
                  } tFramework; 


  /*
   * Enumeration type for Framework definition
   * SW = software
   * HW = hardware
   * SW_FULL           
   * HW_FULL           
   */ 
    parameter tFramework FRAMEWORK = SW_FULL;
   
    // clocks and resets
	parameter CLK_PERIOD = 10ns;
	parameter RESET_TIME = CLK_PERIOD;

	// program specification
	parameter TEST_NUMBER = 1;
	parameter PROG_NUMBER = 5;

        // 

	// halt checking limit (limit for detection of halt instruction)
	parameter ITERATION_COUNT_LIMIT = 1000000;

	// test parameters
	parameter TRANSACTION_COUNT = 10000;
	parameter SEED = 372869151;

endpackage
