/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Mon Mar  4 13:49:04 2013, generated by Codasip HW generator v2.0.0.
 *  \brief  Contains SystemVerilog environment constants.
 */

package sv_codix_ca_param_pkg;

    // Enumeration for verification environment type
    // SW = software 
    // SW_HW = software & hardware
    typedef enum {
                   SW_FULL,
                   SW_HW
                 } tEnv;

    typedef enum { ALL,
                   INFO,
                   NONE
                 } tDebug;

    parameter tEnv VER_ENV = SW_HW;

    
    parameter tDebug DEBUG_LEVEL = ALL;
   
    // clocks and resets
    parameter CLK_PERIOD = 10ns;
    parameter RESET_TIME = CLK_PERIOD;

    // program specification
    parameter TEST_NUMBER = 1;
    parameter PROG_NUMBER = 5;

    // halt checking limit (limit for detection of halt instruction)
    parameter ITERATION_COUNT_LIMIT = 1000000;

    // test parameters
    parameter TRANSACTION_COUNT = 10000;
    parameter SEED = 372869151;

endpackage
