/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Mon Mar  4 13:49:04 2013, generated by Codasip HW generator v2.0.0.
 *  \brief  Contains OVM sequential package.
 */

package sv_codix_ca_seq_pkg;
	import ovm_pkg::*;
	import sv_codix_ca_param_pkg::*;

	`include "ovm_macros.svh"
	`include "transactions.sv"
	`include "sequencer.sv"
	`include "sequence.sv"

endpackage
