/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Thu Jan 17 15:32:01 2013, generated by Codasip HW generator v1.6.0.
 *  \brief  Declaration of wrapper holding all generated interfaces.
 */

// Wrapper is needed for an object in case it has to be stored in the configuration table. Afterwards, other objects can easily manipulate with interface signals.
class DutIfWrapper extends ovm_object;

	// registration of object tools
	`ovm_object_utils( DutIfWrapper )

	// Store references to created interfaces.
	virtual icodix_ca_core_regs icodix_ca_core_regs_if;
	virtual icodix_ca_core_main_instr_hw_instr_hw icodix_ca_core_main_instr_hw_instr_hw_if;
	virtual icodix_ca_mem icodix_ca_mem_if;
	virtual ihalt ihalt_if;
	virtual icodix_ca_in icodix_ca_in_if;
	virtual icodix_ca_out icodix_ca_out_if;

	// Constructor - creates new instance of this class
	function new( string name = "if_wrapper",
		virtual icodix_ca_core_regs icodix_ca_core_regs_if = null,
		virtual icodix_ca_core_main_instr_hw_instr_hw icodix_ca_core_main_instr_hw_instr_hw_if = null,
		virtual icodix_ca_mem icodix_ca_mem_if = null,
		virtual ihalt ihalt_if = null,
		virtual icodix_ca_in icodix_ca_in_if = null,
		virtual icodix_ca_out icodix_ca_out_if = null );

		super.new( name );
		this.icodix_ca_core_regs_if = icodix_ca_core_regs_if;
		this.icodix_ca_core_main_instr_hw_instr_hw_if = icodix_ca_core_main_instr_hw_instr_hw_if;
		this.icodix_ca_mem_if = icodix_ca_mem_if;
		this.ihalt_if = ihalt_if;
		this.icodix_ca_in_if = icodix_ca_in_if;
		this.icodix_ca_out_if = icodix_ca_out_if;
	endfunction: new

endclass: DutIfWrapper

