/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Thu Jan 17 15:32:01 2013, generated by Codasip HW generator v1.6.0.
 *  \brief  Contains SystemVerilog environment constants.
 */

package sv_codix_ca_param_pkg;

	// clocks and resets
	parameter CLK_PERIOD = 10ns;
	parameter RESET_TIME = CLK_PERIOD;

	// program specification
	parameter TEST_NUMBER = 1;
	parameter PROG_NUMBER = 5;

	// halt checking limit (limit for detection of halt instruction)
	parameter ITERATION_COUNT_LIMIT = 1000000;

	// test parameters
	parameter TRANSACTION_COUNT = 1000;
	parameter SEED = 0;

endpackage
