/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Mon Mar  4 13:49:04 2013, generated by Codasip HW generator v2.0.0.
 *  \brief  Contains OVM verification environment package.
 */

package sv_codix_ca_env_pkg;
	import ovm_pkg::*;
	import sv_codix_ca_param_pkg::*;
	import sv_codix_ca_seq_pkg::*;
	import sv_codix_ca_golden_model_pkg::*;

	`include "ovm_macros.svh"
	`include "dut_if_wrapper.sv"
	`include "driver.sv"
	`include "monitor.sv"
	`include "subscriber.sv"
	`include "scoreboard.sv"
      	`include "sorter.sv"
	`include "sender.sv"
	`include "env.sv"
//        `include "../seq_lib/netcope_transaction.sv"
//	`include "dpi/input_wrapper.sv"
//	`include "dpi/output_wrapper.sv"       
//	`include "dpi/dpi_wrapper_pkg.sv"

endpackage
