/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Mon Mar  4 13:49:04 2013, generated by Codasip HW generator v2.0.0.
 *  \brief  Contains OVM test package.
 */

package sv_codix_ca_test_pkg;
	import ovm_pkg::*;
	import sv_codix_ca_param_pkg::*;
	import sv_codix_ca_seq_pkg::*;
	import sv_codix_ca_golden_model_pkg::*;
	import sv_codix_ca_env_pkg::*;

	`include "ovm_macros.svh"
	`include "test.sv"

endpackage
