/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Mon Mar  4 13:49:04 2013, generated by Codasip HW generator v2.0.0.
 *  \brief  Definition of the OVM test class.
 */

// This class is OVM test for codix_ca
class codix_ca_test extends ovm_test;

    // registration of component tools
    `ovm_component_utils( codix_ca_test )

    // member attribute with the verification environment
    // local codix_ca_env m_codix_ca_env;
    local codix_sw_hw  codix_env;

    // Constructor - creates new instance of this class
    function new( string name, ovm_component parent );
        super.new( name, parent );
    endfunction : new

    // build - instantiates child components
    function void build();
        super.build();

        // software version of verification environment
        //if(VER_ENV == SW_FULL) begin
        //    m_codix_ca_env = codix_ca_env::type_id::create( "m_codix_ca_env", this );
        //end

        // hardware accelerated version
        //else if (VER_ENV == SW_HW) begin
            codix_env = codix_sw_hw::type_id::create( "codix_env", this );
        //end

    endfunction: build

    task run();
      //`ovm_info( get_name(), $sformatf("## :: file :: test_lib/test.sv"), OVM_MEDIUM);
    endtask : run

endclass: codix_ca_test
