################################################################################JAKUB
# "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"
#  Generated by Codasip HW generator v2.0.0
#  date: Mon Mar  4 12:01:29 2013
#  brief: Start shell script.
################################################################################


#!/bin/bash

# Change path if necessary
#export PATH=$PATH:
# License file
#export LM_LICENSE_FILE=

cd fve

vsim -do start.fdo $*
