/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Thu Jan 17 15:32:01 2013, generated by Codasip HW generator v1.6.0.
 *  \brief  Declaration of the driver class stimulating input interface of 'codix_ca'.
 */

// Declaration of the class 'codix_ca_input_driver' used for communication with DUTs input interface.
class codix_ca_input_driver extends ovm_driver #( codix_ca_input_transaction );

	// reference to all interfaces
	local DutIfWrapper if_wrapper;
	// registration of component tools
	`ovm_component_utils_begin( codix_ca_input_driver )
		`ovm_field_object( if_wrapper, OVM_DEFAULT | OVM_NOCOMPARE | OVM_NOPRINT | OVM_NORECORD | OVM_NOPACK )
	`ovm_component_utils_end

	// Constructor - creates new instance of this class
	function new( string name, ovm_component parent );
		super.new( name, parent );
	endfunction: new

	// Build - instantiates child components
	function void build();
		super.build();
	endfunction: build

	// run - starts the processing in driver
	task run();
		forever
		begin
			// get next available sequence
			seq_item_port.get_next_item( req );
			// synchronize with DUT
			@(if_wrapper.icodix_ca_in_if.cb );
			// drive ports
			if_wrapper.icodix_ca_in_if.set_codix_ca_irq( req.codix_ca_irq );
			// received sequence is processed
			seq_item_port.item_done();
		end
	endtask: run

endclass: codix_ca_input_driver
