/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Thu Jan 17 15:32:01 2013, generated by Codasip HW generator v1.6.0.
 *  \brief  Contains OVM verification environment package.
 */

package sv_codix_ca_env_pkg;
	import ovm_pkg::*;
	import sv_codix_ca_param_pkg::*;
	import sv_codix_ca_seq_pkg::*;

	`include "ovm_macros.svh"
	`include "dut_if_wrapper.sv"
	`include "driver.sv"
	`include "monitor.sv"
	`include "golden_model.sv"
	`include "subscriber.sv"
	`include "scoreboard.sv"
	`include "env.sv"

endpackage
