#!/bin/bash
# gen_make.sh: Script generating Makefile from list of path/modules
# Author: Viktor Pus <pus@liberouter.org>
#$Id$

# Three parameters required
if [ $# -lt 3 ]; then
   echo "USAGE: gen_make.sh gen|getsd|getdep <output Makefile> path/1/module1.ngc path/2/module2.edf ..."
   exit
fi

if [ $1 != "gen" ]; then
   if [ $1 != "getsd" ]; then
      if [ $1 != "getdep" ]; then
         echo "USAGE: gen_make.sh gen|getsd|getdep <output Makefile> path/1/module1.ngc path/2/module2.edf ..."
         exit
      fi
   fi
fi

MODE=$1
OUTFILE=$2

if [ $MODE = gen ]
then
   echo "Generating $OUTFILE ..."

   echo "#This file was generated by the gen_make.sh script." > $OUTFILE
   echo "" >> $OUTFILE

   # Export all variables to sub-makes
   echo "export" >> $OUTFILE
   echo "unexport MOD" >> $OUTFILE
   echo "unexport CLEANALL_DEPENDS" >> $OUTFILE
   echo "unexport CLEAN_DEPENDS" >> $OUTFILE
   echo "unexport FIRMWARE_BASE" >> $OUTFILE
   echo "" >> $OUTFILE

   # Generate the "all" target
   for  i in $*
   do
      if [ $i != $1 -a $i != $2 ] 
      then
         path=`dirname $i`
         allpaths="$allpaths $path"
         alltargets="$alltargets target_$path"
      fi
   done
   allpaths=`echo $allpaths  | tr " " "\n" | sort -u | tr "\n" " "`
   alltargets=`echo $alltargets  | tr " " "\n" | sort -u | tr "\n" " "`
   echo ".PHONY: clean all $alltargets" >> $OUTFILE
   echo "" >> $OUTFILE
   echo "all : $alltargets" >> $OUTFILE
   echo "" >> $OUTFILE

   # Generate single target for each path
   for p in $alltargets
   do
      echo "$p : " >> $OUTFILE
      for  i in $*
      do
         if [ $i != $1 -a $i != $2 ] 
         then
            path=`dirname $i`
            module=`basename $i`
            if [ $p = target_$path ]
            then
               echo -e "\tcd $path ; \$(MAKE) -e $module" >> $OUTFILE
            fi
         fi
      done
      echo "" >> $OUTFILE
   done

   # Generate the "clean" target
   echo clean : >> $OUTFILE
   for p in $allpaths
   do
      echo -e "\tcd $p ; \$(MAKE) clean" >> $OUTFILE
   done
   echo "" >> $OUTFILE

   echo "Done"
fi

if [ $MODE = "getsd" ]
then
   for  i in $*
   do
      if [ $i != $1 -a $i != $2 ] 
      then
         path=`dirname $i`
         allpaths="$allpaths $path"
      fi
   done
   allpaths=`echo $allpaths  | tr " " "\n" | sort -u | tr "\n" " "  | sed "s/\ /\ -sd\ /g" | sed "s/^/-sd\ /" | sed "s/-sd\ $//"`
   echo $allpaths
fi


if [ $MODE = "getdep" ]
then
   for  i in $*
   do
      if [ $i != $1 -a $i != $2 ] 
      then
         allpaths="$allpaths $i"
      fi
   done
   echo $allpaths
fi
