/******************************************************************************
 *     "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"             *
 ******************************************************************************/
/**
 *  \file
 *  \date   Thu Jan 17 15:32:01 2013, generated by Codasip HW generator v1.6.0.
 *  \brief  Declaration of the class codix_ca_input_sequencer.
 */

// This class manages random inputs for DUT and sends them to driver.
class codix_ca_input_sequencer extends ovm_sequencer #(codix_ca_input_transaction);

	// Provide implementations of virtual methods such as get_type_name and create
	`ovm_sequencer_utils( codix_ca_input_sequencer )

	// Constructor - creates new instance of this class
	function new( string name, ovm_component parent );
		super.new( name, parent );
		`ovm_update_sequence_lib_and_item( codix_ca_input_transaction )
	endfunction: new

endclass: codix_ca_input_sequencer

